version: '3'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: your_db_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: your_db_password
    volumes:
      - ./db-data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx-proxy
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    environment:
      - DOMAIN=example.com
      - EMAIL=your_email@example.com

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: "no"
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL --agree-tos -d $DOMAIN
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx
